### ISSUE TITLE
UVM Mock incompatible with UVM1.2 and UVM_NO_DEPRECATED

### ISSUE THREAD

**Issue by tudortimi** [svunit/svunit#1]
Compiling with the **UVM_NO_DEPRECATED** define leads to compile errors in _svunit_uvm_mock_pkg_.

**Comment by nosnhojn** [comment]
thx tudor. this has been on my list. I know we can use the `ifdef UVM_POST_VERSION_1_1 to switch between the 1.1 and 1.2 compliant code. I hadn't tried the no deprecated though so I'll try give that a whirl on wednesday night.

-neil

**Comment by nosnhojn** [comment]
merged this into the master.
