### ISSUE TITLE
Repo name is silly

### ISSUE THREAD

**Issue by tudortimi** [svunit/svunit#14]
This is a ridiculously pedantic remark, but is there any reason why the repo is called "svunit-code" and not just plain old "svunit"?

**Comment by nosnhojn** [comment]
yes. totally ridiculous. leftover from the initial name given to it by sourceforge.

**Comment by tudortimi** [comment]
You do know you can change it, right? If you do, all old links will still work as GitHub handles this for you: [renaming a repository](https://help.github.com/articles/renaming-a-repository/)
