### ISSUE TITLE
Add possibility to add simulator options

### ISSUE THREAD

**Issue by akika777** [svunit/svunit#147]
This is something that is missing as the script is launching simulation using selected simulator and hardcoded simulator options.
User may want to add manually some options so there should be a runSVUnit option for adding these, e.g.
-so| --sim_options : specify additional simulator options

Regards,
Aleksandar

**Comment by tudortimi** [comment]
This is already possible. It's kind of a silly option name, but what you want is:
```
-r|--r_arg <option>      : specify additional runtime options
```

**Comment by akika777** [comment]
Great, thanks!

Closing
