### ISSUE TITLE
Add support for Xilinx Vivado XSim

### ISSUE THREAD

**Issue by PeterMonsson** [svunit/svunit#148]
SVUnit does not support Xilinx Vivado XSim. I would love to see this supported.

The magic that is needed to run a UVM test (for example) in XSim is:

`Vivado -mode batch -source run.tcl`

Where run.tcl is:

```
exec xvlog -sv -f files.f -L uvm ;
exec xelab top -relax -s top -timescale 1ns/1ps ;
exec xsim top -testplusarg UVM_TESTNAME=basic_test -testplusarg UVM_VERBOSITY=UVM_LOW -runall
```

**Comment by PeterMonsson** [comment]
Two notes:
1) It would be awesome to have a relative path command line option
2) xvlog, xelab, xsim etc, can be called from the command line directly. I don't think that there is a need for the Vivado call.

**Comment by PeterMonsson** [comment]
Vivado XSim will naturally use its own way of specifying standard command line arguments and naturally it doesn't support the star wildcard in -testplusargs...

I wonder whether I am using the wrong approach here by extending runSVUnit.

(Pull request coming up at some point)

**Comment by PeterMonsson** [comment]
See pull request #149

**Comment by tudortimi** [comment]
> I wonder whether I am using the wrong approach here by extending runSVUnit.

At the moment, there's no other way, because SVUnit is part the actual running unit tests, but part script that compiles the production and test code.

This is where what I sent you previously would come in: https://github.com/tudortimi/gradle-hdvl
Gradle is a build automation tool and the `gradle-hdvl` plugin would handle all the mechanics of compiling SystemVerilog code. It would bring us to something like `pip`, but for SV. Using it would remove the need for a `runSVUnit` script. This is a very long ways out, but it's something I'm also working on.

**Comment by CodeStillBroken** [comment]
What is the status of support for Vivado Simulator?  I can see there is some discussions, and people trying to get it to work, but I cant see it as a simulator option when i execute "runSVUnit".  To the best of my knowledge, Vivado is the only freely available (no license required) simulator capable of running UVM. So it seems like an important simulator to support.

**Comment by PeterMonsson** [comment]
The problem with Vivado is that it is just too weird compared to the other simulators. There are probably also still bugs in the implementation of SystemVerilog. 

I recommend that you run buildSVUnit instead of runSVUnit and craft your own run command. See the end of this webpage for ideas: https://uvmkit.com/svunit.html

**Comment by tudortimi** [comment]
I'd like to give it a go myself. The thing holding me back is that Vivado takes such a huge amount of space... Also that I don't know how to resize the Linux partition in my VM.

**Comment by PeterMonsson** [comment]
Here is what I have from ages ago: https://github.com/PeterMonsson/svunit/tree/xilinx-support

**Comment by tudortimi** [comment]
> The problem with Vivado is that it is just too weird compared to the other simulators. There are probably also still bugs in the implementation of SystemVerilog.
> 
> I recommend that you run buildSVUnit instead of runSVUnit and craft your own run command. See the end of this webpage for ideas: https://uvmkit.com/svunit.html

Now I know what you mean:
![vivado-simulator](https://github.com/svunit/svunit/assets/8170909/ea64f464-4e92-4d7f-ba55-e85324ba3ff2)

**Comment by PeterMonsson** [comment]
Enjoy the $fatal(0,”message”) where Vivado just exits without any message whatsoever 

(and the infinite loops - I looked at my diff and the bad memories came back)

**Comment by tudortimi** [comment]
I'm also very happy about the fact that running with or without `--incr` produces different results.
