### ISSUE TITLE
Calling runSVUnit -t <test> with a non-existing test isn't properly signalled as error

### ISSUE THREAD

**Issue by tudortimi** [svunit/svunit#20]
Steps to reproduce:

* run all unit tests by calling runSVUnit without '-t' option
* call runSVUnit -t <some_test_that_doesn't_exist>

With the second call, a warning will be given that the test couldn't be found, but this doesn't stop the script from going forward with a compile and a simulator run. The user will get confused by the output and since the warning is so far up in the history it will most likely be missed.

In this case, runSVUnit should stop. The warning should be changed to an error (the code is in buildSVUnit).

**Comment by nosnhojn** [comment]
yo. fixed/released with v3.24. thanks!
