### ISSUE TITLE
SVUnit Integration: Consider making +SVUNIT_FILTER=* optional to ease integration

### ISSUE THREAD

**Issue by PeterMonsson** [svunit/svunit#211]
I am unable to use runSVUnit at my current client due to the special requirements that they have for their simulation flows.

A small papercut is that I have to supply +SVUNIT_FILTER=* on the command line on each invocation. Please consider making this plusargs optional.

**Comment by tudortimi** [comment]
This should be easy to implement. I think I didn't want to deal with the "what if the plusarg is not set" when I wrote the code initially.

**Comment by tudortimi** [comment]
@PeterMonsson FYI - This didn't autoclose, because GitHub doesn't recognize "solves" as a verb. "Fixed <issue-number>" would have instructed GitHub to also close this issue when the PR mentioning it is merged.

**Comment by PeterMonsson** [comment]
Thanks! I didn’t know that.
