### ISSUE TITLE
Action block for FAIL macros

### ISSUE THREAD

**Issue by eminakgun** [svunit/svunit#219]
Is it possible to include action blocks to be specified when calling `FAIL_* macros?
This helped me to display what is expected versus resulted.

Sample implementation,

```
-`define FAIL_UNLESS(exp) \
+`define FAIL_UNLESS(exp, action=;) \
   begin \
     if (svunit_pkg::current_tc.fail(`"fail_unless`", !(exp), `"exp`", `__FILE__, `__
+      action \
       if (svunit_pkg::current_tc.is_running()) svunit_pkg::current_tc.give_up(); \
     end \
   end
```

**Comment by tudortimi** [comment]
If all you need is printing, then I'd suggest you use `FAIL_UNLESS_LOG`, where you can also pass the string to printed on error.

**Comment by tudortimi** [comment]
I'm looking into better support for built-in prints, which display both the expression and its values, at least for simple things like equality. This is stalled because of various issues with simulator compatibility (what works in one, doesn't work in the other, etc.).

**Comment by eminakgun** [comment]
Just realized after openning the issue that there is FAIL_UNLESS_LOG actually for printing. Can be closed
