### ISSUE TITLE
Cannot add run time options as tcl or do file

### ISSUE THREAD

**Issue by eminakgun** [svunit/svunit#221]
I have a tcl file to run at the beginning, like logging some signals etc since I need further investigations why tests failed.
runSVUnit does not seem to have an option for do files but `r_args`. Unfortunately command below does not work.
Probably r_arg only accepts the only following word.
```
runSVUnit -r_arg "-do sim.tcl"
```

transcript,
```
# sim.tcl
# invalid command name "sim.tcl"
```

How can I solve this problem?

@tudortimi If you can point me where to make changes or additions in Perl script, I can implement myself.

**Comment by tudortimi** [comment]
I think I've seen issues for this in the past. There's probably some bad quoting in the `runSVUnit` script, but I couldn't tell you where exactly. This needs a deeper look.

In the meantime, what I've seen work is to pass something like `-r_arg "-do" -r_arg "sim.tcl"`. Not pretty, but at least it should work.

**Comment by svenka3** [comment]
I believe the DO file works slightly differently in different simulators. In the context of Riviera and Questa/Modelsim I believe we need a "-do" to pass a DO file to vsim command. As far as I see the -r_arg seems more for run-time-args such as "+test_name", "+UVM_CONFIG_DB_TRACE" etc. So I attempted to add a new option to runSVUnit -do and have some basic example working for Riviera-PRO. 

```sh
runSVUnit -r_arg +sw -s riviera -do sim.tcl
```
I see the above leading to a vsim command-line as below:

```log
vsim +sw -c -do "source sim.tcl; run -all; quit" -lib work -l run.log testrunner +SVUNIT_FILTER=*
```

Any interest in this approach? If so I can try on other tools and make it more robust.

**Comment by eminakgun** [comment]
I did the same though since do file is a particular type rather than just passing various switches to simulator. But I've only tried with Questa

```
my $dofile = "";
.
.
.
GetOptions("l|log=s" => \$logfile,
           .............
           "do|do_file=s" => \$dofile,
           "U|uvm" => \$uvm,
           .............
.
.
.
$cmd .= qq! @compileargs; vsim @simargs -lib work -do "do $dofile" -do "run -all; quit" -l $logfile testrunner!;
```

**Comment by svenka3** [comment]
@tudortimi  @nosnhojn - do you want us to create a pull request with DOFILE support as above? Better thoughts? 

Thanks

**Comment by tudortimi** [comment]
@svenka3 I appreciate the enthusiasm, but I don't think adding a `-do` option to `runSVUnit` is the way to go. `-r_arg` is a more generic way of giving control to the user. The code for it should be fixed.

**Comment by tudortimi** [comment]
@eminakgun I tried this and it worked for me:

![image](https://user-images.githubusercontent.com/8170909/222985188-41b44db5-2eaa-40b2-a0bc-35830d1f6b10.png)

![image](https://user-images.githubusercontent.com/8170909/222985211-a7b5b8f9-1901-4e7d-beb4-224c19f7a2f7.png)

If `foo.tcl` is missing, then I get the error you were seeing:

![image](https://user-images.githubusercontent.com/8170909/222985246-41805d78-83fd-4714-9c91-26264fceebc6.png)

![image](https://user-images.githubusercontent.com/8170909/222985256-38d6bc59-a123-4a92-8058-4991b01878dd.png)

**Comment by eminakgun** [comment]
I'm not sure if there was any code changes but I've updated the repo and got it working. As far as I remember the issue was when I specify --r_arg "-do some.tcl", the command in the terminal were like, `-do "do" sim.tcl`.  As you can see the error message in the first entry,
`# invalid command name "sim.tcl"`

But it looks fine now.

**Comment by tudortimi** [comment]
I'll go ahead and close this, since there haven't been any other problems in the meantime.
