### ISSUE TITLE
WSL - Setup.csh needs double-quotes

### ISSUE THREAD

**Issue by svenka3** [svunit/svunit#224]
On WSL I see that Setup.csh does not work, needs double-quotes:

```sh
setenv SVUNIT_INSTALL `pwd`
if ( "$PATH" =~ "*$SVUNIT_INSTALL*" ) then
else
  setenv PATH "${PATH}:$SVUNIT_INSTALL/bin"
endif
```

**Comment by tudortimi** [comment]
This seems to be due to `$PATH` containing spaces, which is more common under Windows than under "pure" Linux.
