### ISSUE TITLE
Unable to invoke modelsim gui because the -c simulator option is always added to the vsim command

### ISSUE THREAD

**Issue by jesseprusi** [svunit/svunit#23]
I used to be able to runSVUnit -s questa -r -gui and this would work fine with the underlying call to qverilog.  Now that only the two step modelsim flow is supported and the command line always has '-c' added by runSVUnit, the '-gui' option cannot be added.

** Error: Mutually exclusive options -c, -gui given.
** Error: Only one of -i, -gui or -c can be used.

**Comment by nosnhojn** [comment]
released v3.22

**Comment by jesseprusi** [comment]
The fix for this has a problem.  The grep for '-c' will also match '-coverage' or any other option starting with '-c'.  I'll submit a patch that looks for spaces in the grep.

**Comment by nosnhojn** [comment]
ha. I looked at it and wondered if we should have an exact match. I guess
the answer is yes :)
