### ISSUE TITLE
Include/Exclude specific tests

### ISSUE THREAD

**Issue by eminakgun** [svunit/svunit#234]
--filter option allows us to run a specific test case added via `SV_TEST. How can we include or exclude multiple tests for a runSVUnit execution?

**Comment by tudortimi** [comment]
Not just, it's also possible to run all tests under a test module using `--filter some_unit_test.*`.

It's also possible to specify multiple filter expressions: `--filter *.test1:*.test2:*.test3`. This should run any test, under any module, that is called either `test1` or `test2` or `test3` (i.e. was defined as `SVTEST(test1)`.

**Comment by tudortimi** [comment]
The feature is modeled after https://google.github.io/googletest/advanced.html#running-a-subset-of-the-tests

Only simple wildcards are supported, meaning only `something.*` or `*.something`, but **not** `something.foo*`.
Negative filters are also supported.

**Comment by tudortimi** [comment]
I'll assume this can be closed. If anything else, feel free to reopen.
