### ISSUE TITLE
Update doc setup to use `build.os`

### ISSUE THREAD

**Issue by tudortimi** [svunit/svunit#269]
https://blog.readthedocs.com/use-build-os-config/

**Comment by PeterMonsson** [comment]
I don't see where .readthedocs.yaml is located in this repo. Is it generated? I am asking as #255 is blocked by readthedocs right now.

**Comment by tudortimi** [comment]
There isn't any. In the past it was enough to just import the project on readthedocs.org and it used defaults. They deprecated this:

![image](https://github.com/svunit/svunit/assets/8170909/27b87d6c-50d7-442a-92e3-633ac646ba66)
