### ISSUE TITLE
Split tests better by simulator

### ISSUE THREAD

**Issue by tudortimi** [svunit/svunit#3]
Not all contributors will have all simulators installed. It would be best to split the tests in an intelligent way to be able to run them in either all simulators or just in one chose simulator.

The test code should somehow be kept common and ideally only the value passed to "runSVUnit -s <>" should be changed. The regression script should either loop over all simulators or, if a command line argument is provides, run the tests for only one simulator.

**Comment by nosnhojn** [comment]
added a simulator array of whatever is found in path and generalized the tests as much as I could. fewer tests so less duplication. each is run against whatever simulators are found.
