### ISSUE TITLE
Can't clone repository via ssh

### ISSUE THREAD

**Issue by Serengan** [svunit/svunit#325]
Please set up ssh keys, i can't clone repository via ssh

![image](https://github.com/user-attachments/assets/97cda1a1-f8a9-4c12-9e3a-aff0a187d202)

**Comment by tudortimi** [comment]
Seems more like a GitHub issues. The repo is public. It might be that GitHub only allows clones through SSH from people with maintainer access.

I also saw this [answer on StackOverflow](https://stackoverflow.com/a/46993922) stating that you need to have an SSH key, otherwise you get an error.

**Comment by Serengan** [comment]
Yes, it seems that the problem is on my side, although I have configured the ssh key. Thanks, I will look for the reason

UPD: The problem was that ctrl+v adds a hidden character
https://stackoverflow.com/questions/53988638/git-fatal-protocol-https-is-not-supported
