### ISSUE TITLE
license confusion

### ISSUE THREAD

**Issue by jlovejoy** [svunit/svunit#53]
Your license notice states "Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements.  See the NOTICE file distributed with this work for additional information regarding copyright ownership.  The ASF licenses this file to you under the Apache License, Version 2.0. . ."

Is that right - is this an ASF project? Your website seems to indicate otherwise - http://agilesoc.com/about/

Either way, are contributions accepted under Apache-2.0 or a contributor license agreement?

**Comment by nosnhojn** [comment]
Ah. Now I know where the cla questions are coming from. The cla references are my mistake. I just barely knew what I was doing when I set this up. I’ll scrub them Friday from the database. The Apache 2.0 is intentional though.

**Comment by jlovejoy** [comment]
great, thanks!

**Comment by jlovejoy** [comment]
you might also want to clean up the references to the ASF ;)
there is some good advice here on this kind of thing, btw: https://reuse.software/

**Comment by nosnhojn** [comment]
I think I got this figured out. closing.
