### ISSUE TITLE
Add support for Xcelium

### ISSUE THREAD

**Issue by tudortimi** [svunit/svunit#55]
Need to allow _xcelium_ and _xrun_ as value for _--simulator_

**Comment by nosnhojn** [comment]
are the incisive and xcelium command lines the same wrt svunit requirements?

**Comment by tudortimi** [comment]
'irun' also works in Xcelium, but issues a lot of deprecation warnings. It might be the case that the options that are renamed also issue deprecation warnings. The args SVUnit uses might have stayed the same.

**Comment by tudortimi** [comment]
I have access to Xcelium. I can do this one, but I wanted to have this issue open as a reminder.

**Comment by tudortimi** [comment]
This has already been done a while back.
