### ISSUE TITLE
runSVUnit deletes files in other out directories

### ISSUE THREAD

**Issue by jesseprusi** [svunit/svunit#7]
I came across an issue when trying to run multiple calls to runSVUnit in the same directory.  I'm submitting them to LSF so they run at the same time and I'm using the -o option to keep each process from interfering with the others.  My directory structure looks like this:

src
src/run_questa
src/run_ius

I'm invoking runSVUnit like this out of the src directory:

bsub runSVUnit -s questa -o run_questa
bsub runSVUnit -s ius -o run_ius

I was experiencing failures because the generated testsuite and testrunner files were being deleted by the clean routine in runSVUnit.  It is cleaning all the testsuite and testrunner files below the src directory rather than just the outdir.

The proposed fix is to change the find call in the clean subroutine to start in $outdir rather than ".".  Would that change break any other use cases?

**Comment by nosnhojn** [comment]
released in v3.15. thanks!
