### ISSUE TITLE
Add export of JUnit XML report

### ISSUE THREAD

**Issue by tudortimi** [svunit/svunit#73]
I remember that we had an issue for this, opened by someone else, but I can't find it.

Now that I started using Jenkins more, I would like to have this as well.

**Comment by tudortimi** [comment]
Found it, it's PR #52. Can we pull this in? Would it help if I resolve the conflict?

**Comment by tudortimi** [comment]
I had a look at #52. I saw it parses the log file to figure out what passed and what failed. This works, but is flaky. If we ever want to change the log message in any way we have to update the parsing as well. It also requires a couple of simulator dependent tweaks

The better approach is to generate the XML file from SystemVerilog. This would be tool agnostic. It would also probably result in less code (assuming we use a library for the XML handling).

**Comment by tudortimi** [comment]
Do we want #52 as an intermediate step?

**Comment by tudortimi** [comment]
We don't necessarily have to generate XML from SystemVerilog immediately. We can generate a file with "raw" pass/fail information, that gets processed by the Python code in #52. This would remove the need for log file parsers.

**Comment by tudortimi** [comment]
The content of #52 would work well as a separate library. IMO, if we want to build anything into SVUnit, we should do it by generating the XML from the SVUnit core classes.

**Comment by vperrin59** [comment]
I support also the addition of this feature. That would greatly help the integration into some Jenkins flow. I will try the branch from #52.
