### ISSUE TITLE
Add possibility to start a single SVTEST

### ISSUE THREAD

**Issue by tudortimi** [svunit/svunit#80]
Something like `runSVUnit -t unit_test_module.svtest_name`.

**Comment by tudortimi** [comment]
`-t` is currently used to specify which test files to compile. By virtue of being the only file that were compiled, only the tests in those files will run.

It's advantageous to only compile a subset of tests. One example is when changes to the API are being made to a unit. In such a case we first want to focus on the test file of the unit we're changing and get that clean. Afterwards, we can start updating any other test files that use this unit. If we were to compile all test files, we might have to start modifying other test files while trying to run the test file for the unit we're changing.

**Comment by tudortimi** [comment]
Instead of changing the behavior of `-t`, we should add a new switch to control which tests should run.

GoogleTest has a `--filter` switch for this purpose. Some examples:

`runSVUnit --filter some_unit_test.some_test` - runs `some_test` defined in `some_unit_test`
`runSVUnit --filter some_unit_test.some_*_test` - runs all tests in `some_unit_test` that match `some_*_test` (e.g `some_foo_test` or `some_bar_test`, but not `another_test`)
`runSVUnit --filter *.some_test` - runs the test(s) called `some_test`, defined in any unit test module

**Comment by tudortimi** [comment]
We should also provide a way of listing all tests in a test run. This is useful for copying paths to use for `--filter`.

GoogleTest has a `--list-tests` option. We should list something like the following:

```
some_unit_test.
  some_test
  some_other_test
some_other_unit_test.
  some_test
some_testsuite.
  yet_another_unit_test.
    some_test
```

**Comment by tudortimi** [comment]
I added a basic implementation of `--filter` in #132

**Comment by justinabate** [comment]
Thanks for your work on this, I intend to try it out soon. Would you consider adding some different sponsorship tiers (e.g. $15/mo, $20/mo)?

**Comment by tudortimi** [comment]
@justinabate Thanks for the support! I added some new tiers to my profile.

**Comment by tudortimi** [comment]
@justinabate What tool are you using (if you can say)? #132 seems to cause issues with Questa/ModelSim Altera Starter Edition, as described in #140.

**Comment by justinabate** [comment]
Same as OP in #140, ModelSim INTEL FPGA STARTER EDITION vsim 2020.1

**Comment by justinabate** [comment]
Filter works for me and I can specify a single test to run. Awesome! Thanks again for your work on this.

Is there a way to specify more than one test name using the --filter switch?

**Comment by tudortimi** [comment]
Currently not, but I'd like to implement it like in [GoogleTest](https://github.com/google/googletest/blob/main/docs/advanced.md#running-test-programs-advanced-options):

> The format of a filter is a ':'-separated list of wildcard patterns (called the positive patterns) optionally followed by a '-' and another ':'-separated pattern list (called the negative patterns). A test matches the filter if and only if it matches any of the positive patterns but does not match any of the negative patterns.

Wildcard patterns are easier to handle than regexes and should be sufficient for filtering.

**Comment by tudortimi** [comment]
Wildcard patterns are easier to handle than regexes.

**Comment by tudortimi** [comment]
I think the best next step toward full `--filter` support as described above, which would help you, is to add support for positive patterns separated by `:`.

**Comment by tudortimi** [comment]
Support for multiple (simple) wildcard expressions added in #155. The next step is to add support for negative expressions.

**Comment by tudortimi** [comment]
Support negative (simple) wildcard expressions was added in #158.

**Comment by tudortimi** [comment]
I'm thinking of closing this issue and leaving the more advanced wildcard handling for later.

**Comment by justinabate** [comment]
Thanks again for your work on this!
