### ISSUE TITLE
`FAIL_XXX macros don't work with if-else blocks

### ISSUE THREAD

**Issue by chschmir** [svunit/svunit#98]
Something like 

```
for (int i = 0; i<2; i++)
  if (i == 0)
    `FAIL_UNLESS(1)
  else
    $display("Skipping check for index '%0d'.", i);
```
will output something like
```
> Skipping check for index '0'.
```
In particular, there is no print for `i==1`.

So reason for this is that `FAIL_UNLESS` expands to something like 
```
if (<some SVUnit check>)
  <stop test>
```
So the entire code block above expands to (with proper indentation):
```
for (int i = 0; i<2; i++)
  if (i == 0)
    if (<some SVUnit check fails>)
      <stop test>
    else
      $display("Skipping check for index '%0d'.", i);
 ```
So, in fact, the print accidentally turns out to be the pass block of the check above.

**Comment by tudortimi** [comment]
Released as part of https://github.com/tudortimi/svunit/releases/tag/v3.34.2
